config/routes.rb
ShoeaddictApp::Application.routes.draw do
  resources :shoes
  root 'shoes#index' # this line added

  

end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  before_action :set_shoe, only: [:show, :edit, :update, :destroy]

  # GET /shoes
  # GET /shoes.json
  def index
    @shoes = Shoe.all
  end

  # GET /shoes/1
  # GET /shoes/1.json
  def show
  end

  # GET /shoes/new
  def new
    @shoe = (params[:key]) ? Shoe.new(picture_params) : Shoe.new
    @shoe.picture.success_action_redirect = new_shoe_url
  end

  # GET /shoes/1/edit
  def edit
  end

  # POST /shoes
  # POST /shoes.json
  def create
    @shoe = Shoe.new(shoe_params)

    respond_to do |format|
      if @shoe.save
        format.html { redirect_to @shoe, notice: 'Shoe was successfully created.' }
        format.json { render action: 'show', status: :created, location: @shoe }
      else
        format.html { render action: 'new' }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoes/1
  # PATCH/PUT /shoes/1.json
  def update
    respond_to do |format|
      if @shoe.update(shoe_params)
        format.html { redirect_to @shoe, notice: 'Shoe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoes/1
  # DELETE /shoes/1.json
  def destroy
    @shoe.destroy
    respond_to do |format|
      format.html { redirect_to shoes_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_shoe
    @shoe = Shoe.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def shoe_params
    params.require(:shoe).permit(:name, :picture, :designer, :description, :color)
  end

  def shoe_params
    params.require(:shoe).permit(:name, :designer, :description, :color, :picture, :key) # add :key
  end
  def picture_params # add this private method
    params.permit(:key)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoeaddictApp</title>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" />
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css "/>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">ShoeAddict App</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/shoes">Shoes</a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <%= yield %>
</div>

<footer>
  <div class="container">
    ShoeAddict App
  </div>
</footer>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

</body>
</html>

app/views/shoes/_form.html.erb
<% unless @shoe.has_picture_upload? %> <!-- this is the code to be added -->
    <%= direct_upload_form_for(@shoe.picture) do |f| %>
        <div class="field">
          <%= f.label :picture %><br>
          <%= f.file_field :picture %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
    <% end %>
<% else %>
    <%= "File \"#{File.basename(@shoe.key)}\" has been uploaded  to S3." %>
<% end %>


<%= form_for @shoe, :html => {:multipart => true} do |f| %>
  <% if @shoe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shoe.errors.count, "error") %> prohibited this shoe from being saved:</h2>

      <ul>
      <% @shoe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :designer %><br>
    <%= f.text_field :designer %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>

  <%= f.hidden_field :key %> <!-- this line added too -->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shoes/edit.html.erb
<h1>Editing shoe</h1>

<%= render 'form' %>

<%= link_to 'Show', @shoe %> |
<%= link_to 'Back', shoes_path %>

app/views/shoes/index.html.erb
<h1>My Loving Shoes</h1> <!-- customized -->
<table class="table table-hover"> <!-- these classes added -->
  <thead>
  <tr>
    <th>Name</th>
    <th>Picture</th>
    <th>Designer</th>
    <th>Description</th>
    <th>Color</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @shoes.each do |shoe| %>
      <tr>
        <td><%= shoe.name %></td>
        <!-- <td>< %= shoe.picture %> # Comment this line -->
        <td><a href="<%= shoe.picture_url %>"><%= image_tag shoe.picture_url(:thumb) if shoe.picture? %></td>
        <td><%= shoe.designer %></td>
        <td><%= shoe.description %></td>
        <td><%= shoe.color %></td>
        <td><%= link_to 'Show', shoe %></td>
        <td><%= link_to 'Edit', edit_shoe_path(shoe) %></td>
        <td><%= link_to 'Destroy', shoe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shoe', new_shoe_path %>

app/views/shoes/new.html.erb
<h1>New shoe</h1>

<%= render 'form' %>

<%= link_to 'Back', shoes_path %>

app/views/shoes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shoe.name %>
</p>

<p>
  <strong>Picture:</strong>
  <!-- < %= @shoe.picture %> commented line -->
  <%= image_tag(@shoe.picture_url, :width => 400) if @shoe.has_picture_upload? %>
</p>

<p>
  <strong>Designer:</strong>
  <%= @shoe.designer %>
</p>

<p>
  <strong>Description:</strong>
  <%= @shoe.description %>
</p>

<p>
  <strong>Color:</strong>
  <%= @shoe.color %>
</p>

<%= link_to 'Edit', edit_shoe_path(@shoe) %> |
<%= link_to 'Back', shoes_path %>